In [ ]:
# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt


--2025-01-27 07:32:28--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.04s   

2025-01-27 07:32:28 (27.5 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [ ]:
!pip install datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 14.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 19.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 15.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 13.7 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.


In [ ]:
from datasets import load_dataset

# Step 1: Load the dataset
dataset = load_dataset("alwalid54321/Arabic_Poems")


README.md:   0%|          | 0.00/2.01k [00:00<?, ?B/s]

poems.csv:   0%|          | 0.00/27.3M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/8875 [00:00<?, ? examples/s]

List of Authors:
1. عبد القادر الجزائري
2. الهدم بن امرئ القيس
3. عبدالله البردوني
4. الراضي بالله
5. عبد الرحمن بن مساعد
6. العباس بن الأحنف
7. المثلم الفزاري
8. هشام الجخ
9. ابن الرعلاء
10. يوسف النبهاني
11. الوأواء الدمشقي
12. محمد ولد ابن ولد أحميدا
13. مصطفى صادق الرافعي
14. الباخرزي
15. حفني ناصف
16. حافظ ابراهيم
17. الإمام الشافعي
18. الجاحظ
19. العقار بن سليل
20. فهد العسكر
21. سهام آل براهمي
22. الأصمعي
23. زياد السعودي
24. ابن دريد الأزدي
25. عنترة بن شداد
26. بغثر بن لقيط الأسدي
27. النابغة الغنوي
28. كريم معتوق
29. أبو الهدى الصيادي
30. الامير منجك باشا
31. ابن حيوس
32. الشريف الرضي
33. إبراهيم اليازجي
34. الأبيوردي
35. لسان الدين بن الخطيب
36. عبد الولي الشميرى
37. مدثر بن إبراهيم بن الحجاز
38. سليم عبدالقادر
39. أم الضحاك المحاربية
40. الميكالي
41. نسيب عريضة
42. عدنان الصائغ
43. صردر
44. إبراهيم عبد القادر المازني
45. محمد المعولي
46. أبو الفضل الكناني
47. ظافر الحداد
48. صخر الغي
49. جورج جرداق
50. ماء العينين
51. الحارث بن حلزة
52. جبلة بن الحارث
53. ابن المُقري
54. ال

In [ ]:

# Step 2: Extract unique author names
author_names = set(poem['poet_name'] for poem in dataset['train'])

# Step 3: Print all authors
print("List of Authors:")
for idx, author in enumerate(author_names, 1):
    print(f"{idx}. {author}")

Dataset({
    features: ['Unnamed: 0', 'poem_title', 'poem_meter', 'poem_verses', 'poem_theme', 'poet_name', 'poet_description', 'poet_era'],
    num_rows: 8875
})
List of Authors:
1. عبد القادر الجزائري
2. الهدم بن امرئ القيس
3. عبدالله البردوني
4. الراضي بالله
5. عبد الرحمن بن مساعد
6. العباس بن الأحنف
7. المثلم الفزاري
8. هشام الجخ
9. ابن الرعلاء
10. يوسف النبهاني
11. الوأواء الدمشقي
12. محمد ولد ابن ولد أحميدا
13. مصطفى صادق الرافعي
14. الباخرزي
15. حفني ناصف
16. حافظ ابراهيم
17. الإمام الشافعي
18. الجاحظ
19. العقار بن سليل
20. فهد العسكر
21. سهام آل براهمي
22. الأصمعي
23. زياد السعودي
24. ابن دريد الأزدي
25. عنترة بن شداد
26. بغثر بن لقيط الأسدي
27. النابغة الغنوي
28. كريم معتوق
29. أبو الهدى الصيادي
30. الامير منجك باشا
31. ابن حيوس
32. الشريف الرضي
33. إبراهيم اليازجي
34. الأبيوردي
35. لسان الدين بن الخطيب
36. عبد الولي الشميرى
37. مدثر بن إبراهيم بن الحجاز
38. سليم عبدالقادر
39. أم الضحاك المحاربية
40. الميكالي
41. نسيب عريضة
42. عدنان الصائغ
43. صردر
44. إبراهيم عبد القادر الم

In [ ]:


# Step 2: Create a dictionary to store poet names and their character counts
poet_char_counts = {}

for poem in dataset['train']:
    poet_name = poem['poet_name']
    poem_text = " ".join(poem['poem_verses'])  # Combine all verses into a single string
    char_count = len(poem_text)  # Count the number of characters in the poem

    if poet_name in poet_char_counts:
        poet_char_counts[poet_name] += char_count
    else:
        poet_char_counts[poet_name] = char_count

sorted_poets = sorted(poet_char_counts.items(), key=lambda x: x[1], reverse=True)

print("List of Poets and Their Character Counts:")
for poet, count in sorted_poets:
    print(f"{poet}: {count} characters")

List of Poets and Their Character Counts:
الشريف الرضي: 2375819 characters
لسان الدين بن الخطيب: 1289849 characters
ابن حيوس: 1129111 characters
ابن المُقري: 1108465 characters
الأبيوردي: 971938 characters
أبو الهدى الصيادي: 941580 characters
حافظ ابراهيم: 851437 characters
يوسف النبهاني: 700750 characters
محمد ولد ابن ولد أحميدا: 586776 characters
محمد المعولي: 517804 characters
الأحنف العكبري: 514566 characters
ظافر الحداد: 472157 characters
العباس بن الأحنف: 391126 characters
الامير منجك باشا: 362475 characters
صردر: 357472 characters
إبراهيم اليازجي: 310590 characters
حفني ناصف: 293109 characters
مصطفى صادق الرافعي: 268746 characters
الوأواء الدمشقي: 237757 characters
إبراهيم عبد القادر المازني: 228910 characters
فهد العسكر: 217127 characters
ابن الزقاق: 206973 characters
مصطفى التل: 180659 characters
ابن دريد الأزدي: 170101 characters
الباخرزي: 150728 characters
عبد القادر الجزائري: 114250 characters
عبد الولي الشميرى: 90303 characters
نسيب عريضة: 87882 characters
الميكالي: 84196 

In [ ]:
import re

# Function to normalize Arabic characters
def normalize_arabic(text):
    # Remove diacritics (e.g., َ, ً, ُ, etc.)
    text = re.sub(r"[\u064B-\u065F\u0670\u06D6-\u06ED]", "", text)

    # Normalize common variations
    text = text.replace("أ", "ا").replace("إ", "ا").replace("آ", "ا")  # Normalize alef
    text = text.replace("ى", "ي")  # Normalize alef maqsura to ya
    text = text.replace("ؤ", "و").replace("ئ", "ي")  # Normalize hamza-related letters
    text = text.replace("ة", "ه")  # Normalize ta marbuta to ha
    return text

poet_name = "ابن المُقري"

filtered_poems = [poem for poem in dataset['train'] if poem['poet_name'] == poet_name]

if not filtered_poems:
    print(f"No poems found for the poet: {poet_name}")
else:
    combined_text = "\n\n".join(
        normalize_arabic(
            "".join(word.strip("[],") for word in poem['poem_verses'])
        )
        for poem in filtered_poems
    )

    print(combined_text[:2000])

    with open("combined_normalized_poems.txt", "w", encoding="utf-8") as file:
        file.write(combined_text)


'رضاك عني رضا الباري به قرنا' 'فمن يضعه ولو اعطي المني غبنا' 'استغفر الله من ذنب اتيت به' 'غضبت منه وقول لم يكن حسنا' 'عضضت كفي حتي كدت اكلها' 'مما ندمت وذابت مهجتي حزنا' 'يا منعما لا اوفي شكره ابدا' 'لو ابذل النفس مرضاته ثمنا' 'هيهات ما ولد موف لوالده' 'معشار ما قلدته كفه مننا' 'هلكت ان لم اكن كالعهد يشملني' 'رضاك عني وهل لي من رضاك غنا' 'ما انت والله في حقي بمتهم' 'ولا ملوم ولكن الملوم انا' 'كم نعمه لك مثل الطوق في عنقي' 'وكم يد لك بيضا في يدي ومنا' 'شلت يدي حين اتي الامر تكرهه' 'وحين اصغي لما لا تشتهي اذنا' 'اعرضت عني فقام الدهر يرشقني' 'بصرف احداثه من ها هنا وهنا' 'وهنت عند رجال لا خلاق لهم' 'فمن اناديه لوي راسه وثني' 'اعراض وجهك عني قد لقيت به' 'امرا اغبطت له في الترب من دفنا' 'قد كنت اشفق بي مني فيا اسفا' 'علي مكانتي الاولي ويا حزنا' 'اذا شكار ضرا من زمانهم' 'فحالتي تلك لا اشكو لها الزمنا' 'واليوم اصبحت مما انت تسعدني' 'مستصغرا في عيون الناس ممتهنا' 'وانت جاهي اذا هملتني انهدمت' 'قواعد كنت قد اسستها وبنا' 'هجرت غيرك خوفا ان يقول فتي' 'ما كان ذا لابيه هل يكون لنا' 'وما كمثلك في اب

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

In [ ]:
batch_size = 32
block_size = 256
max_iters = 5000
eval_interval = 300
learning_rate = 3e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2


In [ ]:
# with open('input.txt', 'r',encoding='utf-8') as f:
#   text = f.read()

In [ ]:
text = combined_text

In [ ]:
print(len(text))

524346


In [ ]:
print(text[:1000])

'رضاك عني رضا الباري به قرنا' 'فمن يضعه ولو اعطي المني غبنا' 'استغفر الله من ذنب اتيت به' 'غضبت منه وقول لم يكن حسنا' 'عضضت كفي حتي كدت اكلها' 'مما ندمت وذابت مهجتي حزنا' 'يا منعما لا اوفي شكره ابدا' 'لو ابذل النفس مرضاته ثمنا' 'هيهات ما ولد موف لوالده' 'معشار ما قلدته كفه مننا' 'هلكت ان لم اكن كالعهد يشملني' 'رضاك عني وهل لي من رضاك غنا' 'ما انت والله في حقي بمتهم' 'ولا ملوم ولكن الملوم انا' 'كم نعمه لك مثل الطوق في عنقي' 'وكم يد لك بيضا في يدي ومنا' 'شلت يدي حين اتي الامر تكرهه' 'وحين اصغي لما لا تشتهي اذنا' 'اعرضت عني فقام الدهر يرشقني' 'بصرف احداثه من ها هنا وهنا' 'وهنت عند رجال لا خلاق لهم' 'فمن اناديه لوي راسه وثني' 'اعراض وجهك عني قد لقيت به' 'امرا اغبطت له في الترب من دفنا' 'قد كنت اشفق بي مني فيا اسفا' 'علي مكانتي الاولي ويا حزنا' 'اذا شكار ضرا من زمانهم' 'فحالتي تلك لا اشكو لها الزمنا' 'واليوم اصبحت مما انت تسعدني' 'مستصغرا في عيون الناس ممتهنا' 'وانت جاهي اذا هملتني انهدمت' 'قواعد كنت قد اسستها وبنا' 'هجرت غيرك خوفا ان يقول فتي' 'ما كان ذا لابيه هل يكون لنا' 'وما كمثلك في اب

In [ ]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 'ءابتثجحخدذرزسشصضطظعغفقكلمنهوي
32


In [ ]:
stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

print(encode("بلال"))
print(decode(encode("بلال")))

[5, 26, 4, 26]
بلال


In [ ]:
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape,data.dtype)
print(data[:100])

torch.Size([524346]) torch.int64
tensor([ 2, 13, 18,  4, 25,  1, 21, 28, 31,  1, 13, 18,  4,  1,  4, 26,  5,  4,
        13, 31,  1,  5, 29,  1, 24, 13, 28,  4,  2,  1,  2, 23, 27, 28,  1, 31,
        18, 21, 29,  1, 30, 26, 30,  1,  4, 21, 19, 31,  1,  4, 26, 27, 28, 31,
         1, 22,  5, 28,  4,  2,  1,  2,  4, 15,  6, 22, 23, 13,  1,  4, 26, 26,
        29,  1, 27, 28,  1, 12, 28,  5,  1,  4,  6, 31,  6,  1,  5, 29,  2,  1,
         2, 22, 18,  5,  6,  1, 27, 28, 29,  1])


In [ ]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [ ]:
x = train_data[:block_size] # [0,1,2,3,4]
y = train_data[1:block_size+1] # [1,2,3,4,5] shifted ->
for t in range(block_size):
  context = x[:t+1]
  target = y[t]
  print(f"when input is {context} target is {target}")

when input is tensor([18]) target is 47
when input is tensor([18, 47]) target is 56
when input is tensor([18, 47, 56]) target is 57
when input is tensor([18, 47, 56, 57]) target is 58
when input is tensor([18, 47, 56, 57, 58]) target is 1
when input is tensor([18, 47, 56, 57, 58,  1]) target is 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) target is 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) target is 58


In [ ]:
torch.manual_seed(1337)

#batch_size = 4
#block_size = 8

def get_batch(split):
  data = train_data if split == 'train' else val_data
  ix = torch.randint(len(data) - block_size, (batch_size,))
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  x,y = x.to(device), y.to(device)
  return x,y

xb,yb = get_batch('train')
# print('inputs:')
# print(xb.shape)
# print(xb)
# print('targets:')
# print(yb.shape)
# print(yb)

# print('----')


# for b in range(batch_size):
#   for t in range(block_size):
#     context = xb[b,:t+1]
#     target = yb[b,t]
#     print(f"when input is {context.tolist()} target is {target}")

In [ ]:
@torch.no_grad()
def estimate_loss():
  out = {}
  m.eval()
  for split in ['train','val']:
    losses = torch.zeros(eval_iters)
    for k in range(eval_iters):
      X,Y = get_batch(split)
      logits,loss = m(X,Y)
      losses[k] = loss.item()
    out[split] = losses.mean()
  m.train()
  return out

In [ ]:
class Feedforward(nn.Module):
  def __init__(self,n_embd):
    super().__init__()
    self.net = nn.Sequential(
        nn.Linear(n_embd,4 * n_embd),
        nn.ReLU(),
        nn.Linear(4 * n_embd,n_embd)
    )
  def forward(self,x):
    return self.net(x)

In [ ]:
class Decoder(nn.Module):
  def __init__(self,n_embd,n_head):
    super().__init__()
    head_size = n_embd // n_head
    self.sa_head = MultiHeadAttention(n_head,head_size)
    self.ffwd = Feedforward(n_embd)
    self.ln1 = nn.LayerNorm(n_embd)
    self.ln2 = nn.LayerNorm(n_embd)

  def forward(self,x):
    x = x + self.sa_head(self.ln1(x))
    x = x + self.ffwd(self.ln2(x))

    return x

In [ ]:

class PicoGPT(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
    self.position_embedding_table = nn.Embedding(block_size, n_embd)
    #self.blocks = nn.Sequential(*[Decoder(n_embd,4),Decoder(n_embd,4),Decoder(n_embd,4),nn.LayerNorm(n_embd))
    self.blocks = nn.Sequential(*[Decoder(n_embd,n_head=n_head) for _ in range(n_layer)])
    self.ln_f = nn.LayerNorm(n_embd)
    self.ffwd = Feedforward(n_embd)
    self.lm_head = nn.Linear(n_embd,vocab_size)

  def forward(self, idx, targets=None):
    B ,T = idx.shape
    tok_emb = self.token_embedding_table(idx) # (B,T,C) each charachter has (Vocab size) outputs
    pos_emb = self.position_embedding_table(torch.arange(T,device=device)) # (T,C) (STUPID POSITIONAL ENCODING)
    x = tok_emb + pos_emb
    x = self.blocks(x)
    logits = self.lm_head(x)
    if targets is None:
      loss = None
    else:
      B , T , C  = logits.shape
      logits = logits.view(B*T,C) # collapsing B T
      #print("hh",targets.shape)
      targets = targets.view(B*T)
      loss = F.cross_entropy(logits,targets) # (B,C,T)

    return logits,loss
  def generate(self,idx,max_new_tokens):
    for _ in range(max_new_tokens):
      idx_crop = idx[:,-block_size:]
      logits,loss = self(idx_crop)
      logits = logits[:,-1,:]
      probs = F.softmax(logits,dim=-1)
      idx_next = torch.multinomial(probs,num_samples=1)
      idx = torch.cat((idx,idx_next),dim=1)
    return idx


#print(xb)
#print(yb)

#print(decode(m.generate(idx,max_new_tokens=100)[0].tolist()))

In [ ]:
class Head(nn.Module):
  def __init__(self,head_size):
    super().__init__()
    self.key = nn.Linear(n_embd,head_size,bias=False)
    self.query = nn.Linear(n_embd,head_size,bias=False)
    self.value = nn.Linear(n_embd,head_size,bias=False)
    self.register_buffer('tril',torch.tril(torch.ones(block_size,block_size)))
    self.dropout = nn.Dropout(dropout)

  def forward(self,x):
    B,T,C = x.shape
    k = self.key(x)
    q = self.query(x)
    wei = q @ k.transpose(-2,-1) * C**-0.5
    wei = wei.masked_fill(self.tril[:T,:T] == 0,float('-inf'))
    wei = F.softmax(wei,dim=-1)
    wei = self.dropout(wei)
    v = self.value(x)
    out = wei @ v
    return out


In [ ]:
class MultiHeadAttention(nn.Module):
  def __init__(self,num_heads,head_size):
    super().__init__()
    self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
    self.proj = nn.Linear(n_embd,n_embd)
    self.dropout = nn.Dropout(dropout)

  def forward(self,x):
    out = torch.cat([h(x) for h in self.heads],dim=-1)
    out = self.dropout(self.proj(out))
    return out

In [ ]:
# optimizer = torch.optim.AdamW(m.parameters(),lr=1e-4)

In [ ]:
# for steps in range(10000):
#   xb, yb = get_batch('train')

#   logits,loss = m(xb,yb)
#   optimizer.zero_grad(set_to_none=True)
#   loss.backward()
#   optimizer.step()
# print(loss.item())

3.6591148376464844


In [ ]:
m = PicoGPT(vocab_size)
m = m.to(device)

optimizer = torch.optim.AdamW(m.parameters(), lr=learning_rate)

for iter in range(max_iters):
    if iter % eval_interval == 0:
        losses = estimate_loss()
        print(f"step: {iter}: train loss: {losses['train']:.4f}, val loss: {losses['val']:.4f}")

    xb, yb = get_batch('train')
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

step: 0: train loss: 3.8686, val loss: 3.8686
step: 300: train loss: 2.4765, val loss: 2.4648
step: 600: train loss: 2.1881, val loss: 2.1873
step: 900: train loss: 2.0633, val loss: 2.0653
step: 1200: train loss: 1.9602, val loss: 1.9689
step: 1500: train loss: 1.8844, val loss: 1.9079
step: 1800: train loss: 1.8187, val loss: 1.8608
step: 2100: train loss: 1.7736, val loss: 1.8294
step: 2400: train loss: 1.7282, val loss: 1.8079
step: 2700: train loss: 1.6864, val loss: 1.7918
step: 3000: train loss: 1.6495, val loss: 1.7829
step: 3300: train loss: 1.6087, val loss: 1.7707
step: 3600: train loss: 1.5640, val loss: 1.7734
step: 3900: train loss: 1.5223, val loss: 1.7816
step: 4200: train loss: 1.4786, val loss: 1.7927
step: 4500: train loss: 1.4298, val loss: 1.8068
step: 4800: train loss: 1.3729, val loss: 1.8147


In [ ]:
context = torch.zeros((1,1),dtype=torch.long,device=device)
print(context.shape)
print(decode(m.generate(context,max_new_tokens=500)[0].tolist()))

torch.Size([1, 1])

كم في الاعار شديد' 'حسبي الي السن ان تبتن' 'ظهرت الفرجاء لا يخفي بخلي' 'اخو باق العجا منه الخير' 'يجود البحر اليوم بسير الردي' 'فيا للفقطات اخسر المعود' 'للابحر الابن الليالي كعوده' 'للصاهد الابحر والهم بالدعا' 'الري انه عهد كانت بيض' 'واخجل يستغضي فالهوي العجاذل' 'لي عطش فخر ذي والمنطق حاجه' 'وفاعات كل ارض لي حق له' 'فعلت مكانات عليه تسكينها' 'لما تلم منه المدح في الاخمر' 'لا زاجتها بملك توم ركيبه' 'فوزت بسم لكي وعقوق عيونه' 'لم تهوي الليل عنك خريقه التمايه' 'من لا يريك بقاء رد العيونه' 'كذب يح


In [ ]:
torch.manual_seed(1337)
B,T,C = 4,8,2
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
xbow = torch.zeros((B,T,C))
for b in range(B):
  for t in range(T):
    xprev = x[b,:t+1]
    xbow[b,t] = torch.mean(xprev,0)

In [ ]:
wei = torch.tril(torch.ones(T,T))
wei = wei / wei.sum(1,keepdim=True)
xbow2 = wei @ x

torch.allclose(xbow,xbow2)

False

In [ ]:
torch.manual_seed(1337)
B,T,C =  4,8,32
x = torch.randn(B,T,C)
head_size = 16
key = nn.Linear(C,head_size,bias=False)
query = nn.Linear(C,head_size,bias=False)
value = nn.Linear(C,head_size,bias=False)
k = key(x) # B T 16
q = query(x) # B T 16
wei = q @ k.transpose(-2,-1) # B T 16 @ B 16 T --> B T T

tril = torch.tril(torch.ones(T,T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril==0,float('-inf'))
wei = F.softmax(wei,dim=-1)
v = value(x)
out = wei @ v
out.shape

torch.Size([4, 8, 32])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [ ]:
xbow[0]

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])

In [ ]:
torch.manual_seed(42)
a = torch.ones(3,3)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[14., 16.],
        [14., 16.],
        [14., 16.]])


In [ ]:
torch.save(m.state_dict(), 'picogpt_weights.pth')



##Inference

In [ ]:
# First recreate the model architecture
model = PicoGPT(vocab_size=32)  # Use the same vocab_size as during training

# Load the saved weights
model.load_state_dict(torch.load('picogpt_weights.pth'))
model.eval()
model.to(device)

<ipython-input-114-41eed76683c1>:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load('picogpt_weights.pth'))


PicoGPT(
  (token_embedding_table): Embedding(32, 384)
  (position_embedding_table): Embedding(256, 384)
  (blocks): Sequential(
    (0): Decoder(
      (sa_head): MultiHeadAttention(
        (heads): ModuleList(
          (0-5): 6 x Head(
            (key): Linear(in_features=384, out_features=64, bias=False)
            (query): Linear(in_features=384, out_features=64, bias=False)
            (value): Linear(in_features=384, out_features=64, bias=False)
            (dropout): Dropout(p=0.2, inplace=False)
          )
        )
        (proj): Linear(in_features=384, out_features=384, bias=True)
        (dropout): Dropout(p=0.2, inplace=False)
      )
      (ffwd): Feedforward(
        (net): Sequential(
          (0): Linear(in_features=384, out_features=1536, bias=True)
          (1): ReLU()
          (2): Linear(in_features=1536, out_features=384, bias=True)
        )
      )
      (ln1): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (ln2): LayerNorm((384,), eps=1e-05

In [ ]:
def generate_text(model, start_token, max_new_tokens=100):
    # Convert starting token to tensor
    idx = torch.tensor([[start_token]], dtype=torch.long, device=device)

    # Generate text
    with torch.no_grad():
        for _ in range(max_new_tokens):
            # Get predictions
            logits, _ = model(idx)

            # Focus on last time step
            logits = logits[:, -1, :]  # (B, C)

            # Get probabilities
            probs = F.softmax(logits, dim=-1)

            # Sample from distribution
            idx_next = torch.multinomial(probs, num_samples=1)

            # Append to sequence
            idx = torch.cat((idx, idx_next), dim=1)

    return idx

# Example usage
start_token = 0  # Your starting token index
generated_sequence = generate_text(model, start_token, max_new_tokens=100)
print(decode(generated_sequence[0].tolist()))  # Assuming you have a decode function


'تممعنا عن قدما لباقيك العدي' 'متي يذيق الاعدا علي الشرك' 'فقمت واي عليك وكل ينظر'

'لقد احل طود بسي
